### ISSUE TITLE
Working example for encoding/decoding

### ISSUE THREAD

**Issue by philipdexter** [ujamjar/oh261#1]
I've been playing around with the sample encoding/decoding programs in the `lib_test` directory. Unfortunately I can't get them to work. For example, encoding the first qcif format yuv file from [http://trace.eas.asu.edu/yuv/](http://trace.eas.asu.edu/yuv/) gives me an unplayable mp4 file.
Also, trying to decode the [mp4 file](https://gist.githubusercontent.com/andrewray/d418752f3f8745df61fa/raw/49a877ff493707e628da63a855a83fc7f8dc77f6/cifakiyo128.p64) that was used in the impressive [oh261 ocaml notebook example](https://andrewray.github.io/iocamljs/oh261.html) crashes the decoder.

I've also tried converting some videos to yuv using ffmpeg to encode into h261 however none result in playable mp4 files. There are several different yuv formats though, so I might be choosing the wrong one.

Are there some known yuv/mp4 files that the encoder/decoder can work with? Or perhaps I need to make some changes in the sample programs to make them work for specific files?

I'm using ocaml 4.03.0.

Thank you very much

**Comment by andrewray** [comment]
The encoder does not work I am afraid (I think an intra only encoder was almost working though).

The decoder should work.  I've had a quick look and (from this repo)

```
./oh261d.byte -i bits/cifakiyo128.p64 -o - | oplay -s cif
```

seems to work OK.  (you can `opam install oplay` for the viewer).

**Comment by philipdexter** [comment]
Yes, that does indeed work, great.

However, playing until the end using oplay or using `-o TEST.yuv` still crashes:

``` bash
$ ./decoder -i ../../oh261/bits/cifakiyo128.p64 -o - | oplay -s cif -v
in-file: 
diff-file: 
size-in: 352x288
size-out: 352x288
format: IYUV
framerate: 30
fullscreen: false
Fatal error: exception Ovideo.Bits.Reader(S).Out_of_bits
Fatal error: exception End_of_file
$ ./decoder -i ../../oh261/bits/cifakiyo128.p64 -o TEST.yuv
Fatal error: exception Ovideo.Bits.Reader(S).Out_of_bits
```

But then converting TEST.yuv to something like H.264 using

``` bash
ffmpeg -f rawvideo -vcodec rawvideo -s 352x288 -r 30 -pix_fmt yuv420p -i TEST.yuv -c:v libx264 -preset ultrafast -qp 0 TEST.mp4
```

produces a working file.

So it seems the crash is not fatal

**Comment by andrewray** [comment]
Technically speaking, the decoder is raising this exception because it really has seen a problem in the bitstream.  H.261 does not byte align each video frame within the bitstream, therefore, there are likely to be a few stray bits at the end of the file.  The decoder is seeing these bits and saying I was trying to decode something but ran out of bits.

Practically speaking it could try and detect this situation (it happened while decoding a picture start code, or detects that this is the final byte of the stream).  Or just ignore it with a `try...with` block.

**Comment by philipdexter** [comment]
Very informative, thanks for your help
